steps:
  - name: 'node:19'
    entrypoint: 'npm'
    args: ['install']
  - name: 'node:19'
    entrypoint: 'npm'
    args:
      - 'run'
      - 'docs:build'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gsutil'
    args:
      - '-m'
      - 'rsync'
      - '-r'
      - '-d'
      - 'docs/.vitepress/dist/'
      - 'gs://kagi-us-east1-docs-vitepress/'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'compute'
      - 'url-maps'
      - 'invalidate-cdn-cache'
      - 'kagi-prod-urlmap-anycast-em'
      - '--path'
      - '/*'
      - '--host'
      - 'help.kagi.com'
      - '--project'
      - 'kagi-global'
