blank_issues_enabled: false
contact_links:
  - name: Documentation Q&A Forum
    url: https://github.com/kagisearch/kagi-docs/discussions/categories/q-a
    about: Have a question about the documentation or APIs? You can discuss them here!

  - name: Kagi Search API Feature Requests & Ideas
    url: https://github.com/kagisearch/kagi-docs/discussions/categories/feature-requests-ideas
    about: If you have an idea that you would like to see in the Search API, you can discuss them here!

  - name: Kagi Search feedback, bug reports, and feature requests
    url: https://kagifeedback.org
    about: If you have found a bug or have feedback for Kagi Search that is unrelated to the API or documentation, please open a ticket on this forum.

  - name: Kagi Search Discord Server
    url: https://kagi.com/discord
    about: Chat with the Kagi Search developers and community for small questions, sharing ideas, and casual discussion.

  - name: Orion Browser feedback, bug reports, and feature requests
    url: https://orionfeedback.org
    about: If you have found a bug or have feedback for the Orion Browser that is unrelated to its documentation, please open a ticket on this forum.

  - name: Orion Browser Discord Server
    url: https://discord.gg/EMMzT57hQT
    about: Chat with the Orion developers and community for small questions, sharing ideas, and casual discussion.
